### PR TITLE
fix: change http-status to handle status ranges

### LINKED ISSUE #219: change http-status react component to handle status ranges
**Describe the bug**
currently component handles only statuses numbered as static numbers: `200 | 201 | 404 | 500`.
But!  http statuses may have different numbers at some cases...
http requests can have status number as one of following number ranges as it says [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)

**Expected behavior**

**Screenshots**
image

### PR DESCRIPTION
**Pull request by shootermv**
## Description

changes http-status component to handle statuses numbers of specific status ranges.
like status 219 , which before was mapped to `default` now mapped to `success`

Closes #219 

## How to Test

Outline the steps to test the changes made in this pull request. Provide as much detail as necessary so that reviewers can easily verify the changes.

1. Step 1
2. Step 2
3. ...

## Additional Notes

Include any other relevant information, context, or considerations related to this pull request.

## Checklist

Please make sure you've done the following before submitting this pull request:

- [ ] Ran all existing tests to ensure they pass.
- [ ] Added new tests to cover the changes (if applicable).
- [ ] Reviewed the code for any potential issues or bugs.
- [ ] Updated the documentation (if needed) to reflect the changes.
- [ ] Squashed your commits into a single logical commit (if necessary).

### CODE REVIEW

File: traffic-dashboard/src/components/http-status/http-status.tsx [hunk 1]
```diff
@@ -11,18 +11,16 @@ export const HttpStatus: React.FC<IHttpMethodProps> = ({ status }) => {
...
-  }
+  /* maps statuses numbers to color string e.g. 201 -> success */
+  const statusesMap = {
+    2: "success",
+    4: "warning",
+    5: "error",
+  } as any;
+  return statusesMap[status.toString().slice(0, 1)] || "default";
 }
+/*tests (TODO: add real ones)*/
```
Comment (idodav) [inline traffic-dashboard/src/components/http-status/http-status.tsx:22]: Please remove the comment.
If you have a TODO you could open an issue for it instead.

**Review by idodav — APPROVED** [review]

**Comment by idodav** [comment]
@shootermv Thank you very much. This is great!
